name: Unit Tests

runs: 
  using: "composite"
  steps:
    - name: Setup pytest environment
      shell: bash
      run: pip install pytest pytest-cov
    - name: "Run tests with pytest"
      shell: bash
      run: pytest --cov-fail-under=80 test/unitest.py