#!/bin/bash

source .git/hooks/config
source .git/hooks/log

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

allowed_prefix=$(IFS='|'; echo "${allowed_message_prefix[*]}")
regex="(${allowed_prefix}):"

if ! echo "$commit_msg" | grep -E -q "$regex"; then
    error "commit的message格式不符合协作规范。"
    tips "请按照协作文档修改message的格式。"
    tips "协作文档请参照${github_cooperation_docs}"
    info "commit流程终止，请重新commit。"
    exit 1
fi